services:
    sylius.importers_registry:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\ImporterRegistry
        arguments:
            - FriendsOfSylius\SyliusImportExportPlugin\Importer\ImporterInterface
            - importer

    sylius.factory.csv_reader:
        class: Port\Csv\CsvReaderFactory
        arguments:
            - 0

    sylius.factory.excel_reader:
        class: Port\Excel\ExcelReaderFactory
        arguments:
            - 1

    sylius.controller.import_data:
        class: FriendsOfSylius\SyliusImportExportPlugin\Controller\ImportDataController
        arguments:
            - "@sylius.importers_registry"
            - "@router"
            - "@session"

    sylius.importer.payment_methods.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\PaymentMethodsImporter
        arguments:
            - "@sylius.factory.csv_reader"
            - "@sylius.factory.payment_method"
            - "@sylius.repository.payment_method"
            - "@sylius.manager.payment_method"
        tags:
            - { name: sylius.importer, type: payment_method, format: csv }

    sylius.importer.payment_methods.excel:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\PaymentMethodsImporter
        arguments:
            - "@sylius.factory.excel_reader"
            - "@sylius.factory.payment_method"
            - "@sylius.repository.payment_method"
            - "@sylius.manager.payment_method"
        tags:
            - { name: sylius.importer, type: payment_method, format: excel }

    sylius.importer.tax_categories.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\TaxCategoriesImporter
        arguments:
            - "@sylius.factory.csv_reader"
            - "@sylius.factory.tax_category"
            - "@sylius.repository.tax_category"
            - "@sylius.manager.tax_category"
        tags:
            - { name: sylius.importer, type: tax_category, format: csv }

    sylius.importer.tax_categories.excel:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\TaxCategoriesImporter
        arguments:
            - "@sylius.factory.excel_reader"
            - "@sylius.factory.tax_category"
            - "@sylius.repository.tax_category"
            - "@sylius.manager.tax_category"
        tags:
            - { name: sylius.importer, type: tax_category, format: excel }
